/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.sql.*;
import dao.Utilitario;
import javax.swing.*;
import modelo.Emprestimo;
import modelo.Ferramenta;
import dao.EmprestimoDAO;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Amigo;

/**
 *
 * @author guiho
 */
public class FrmEmprestimoDeFerramentas extends javax.swing.JFrame {

    private Ferramenta ferramenta;
    private Amigo amigo;
    /**
     * Creates new form FrmEmprestimoDeFerramentas
     */
    public FrmEmprestimoDeFerramentas() {
        initComponents();
        
        this.amigo = new Amigo();
        this.ferramenta = new Ferramenta();
        inicializarJBCNomeAmigo();
        inicializarJBCNomeFerramenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBConfirmar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCBNomeAmigo = new javax.swing.JComboBox<>();
        jCBNomeFerramenta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Empréstimo de Ferramentas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nome do Amigo:");

        JBConfirmar.setText("Confirmar");
        JBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBConfirmarActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nome da Ferramenta:");

        jCBNomeAmigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCBNomeAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNomeAmigoActionPerformed(evt);
            }
        });

        jCBNomeFerramenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCBNomeFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNomeFerramentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(JBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBNomeAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBNomeFerramenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBNomeAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBNomeFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    /**
     * Conecta com a coluna nome da tb_amigos do banco de dados.
     */
    private void inicializarJBCNomeAmigo(){
        
        ArrayList<Amigo> listaAmigo = amigo.ListaAmigo();
        for (Amigo objeto : listaAmigo) {
            jCBNomeAmigo.addItem(objeto.getIdAmigo() + "- " + objeto.getNomeAmigo());
        }

    }
    
    /**
     * Conecta com a coluna IdFerramentas da tb_ferramentas e coleta o nome da ferramenta
     * para usar no jComboBox.
     */
    private void inicializarJBCNomeFerramenta(){
        
            ArrayList<Ferramenta> listaFerramenta = ferramenta.ListaFerramenta();
        for (Ferramenta objeto : listaFerramenta) {
            jCBNomeFerramenta.addItem(objeto.getIdFerramentas() + "- " + objeto.getNomeFerramentas());
        }

    }
    
    
    /*
    Confirma a ação de emprestar, cadastrando a ferrementa e o amigo na lista de emprestimo.
    
    Caso o amigo já tenha um emprestimo aparecerá um aviso perguntando se realmente quer emprestar.
    
    Caso a ferramenta já esteja emprestada não será possivel emprestar.
    */
    private void JBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBConfirmarActionPerformed
        // TODO add your handling code here:
     try {
    int conf = 0;

    int posicaoFerramenta = jCBNomeFerramenta.getSelectedIndex();
    int posicaoAmigo = jCBNomeAmigo.getSelectedIndex();
    ArrayList<Ferramenta> listaFerramenta = ferramenta.ListaFerramenta();
    ArrayList<Amigo> listaAmigo = amigo.ListaAmigo();
    Emprestimo emprestimo = new Emprestimo();

    if (!listaFerramenta.get(posicaoFerramenta).getDisponibilidadeFerramenta(listaFerramenta.get(posicaoFerramenta).getIdFerramentas())) {
        throw new Mensagem("Ferramenta já emprestada");
    }

    int idAmigo = listaAmigo.get(posicaoAmigo).getIdAmigo();
    if (amigo.possuiEmprestimoAtivo(idAmigo)) {
        conf = JOptionPane.showConfirmDialog(null, "Este amigo já possui um empréstimo ativo, deseja continuar?");
    }

    int idFerramenta = listaFerramenta.get(posicaoFerramenta).getIdFerramentas();
    String DataInicio = LocalDate.now().toString();
    
    if (conf == 0) {
        if (emprestimo.insertEmprestimoBD(idAmigo, idFerramenta, DataInicio)) {
            JOptionPane.showMessageDialog(null, "Empréstimo cadastrado com sucesso");
            ferramenta.updateFerramentaDB(idFerramenta, listaFerramenta.get(posicaoFerramenta).getNomeFerramentas(), listaFerramenta.get(posicaoFerramenta).getMarcaFerramentas(), listaFerramenta.get(posicaoFerramenta).getCustoFerramentas());
        }
    }
} catch (Mensagem erro) {
    JOptionPane.showMessageDialog(null, erro.getMessage());
}
    }//GEN-LAST:event_JBConfirmarActionPerformed

    private void jCBNomeAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNomeAmigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBNomeAmigoActionPerformed

    private void jCBNomeFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNomeFerramentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBNomeFerramentaActionPerformed
    /*
    Carrega a tabela de emprestimos, por isso puxa uma tabela de amigos e uma de ferramentas.
    */
    public void carregaCBFerramenta() {
        ArrayList<Ferramenta> listaFerramenta = ferramenta.ListaFerramenta();
        for (Ferramenta objeto : listaFerramenta) {
            jCBNomeFerramenta.addItem(objeto.getIdFerramentas() + "- " + objeto.getNomeFerramentas());
        }

    }

    public void carregaCBAmigo() {
        ArrayList<Amigo> listaAmigo = amigo.ListaAmigo();
        for (Amigo objeto : listaAmigo) {
            jCBNomeAmigo.addItem(objeto.getIdAmigo() + "- " + objeto.getNomeAmigo());
        }

    }       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoDeFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoDeFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoDeFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmprestimoDeFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmprestimoDeFerramentas().setVisible(true);
            }
        });
    }

    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBConfirmar;
    private javax.swing.JComboBox<String> jCBNomeAmigo;
    private javax.swing.JComboBox<String> jCBNomeFerramenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
